"""
Django settings for YaserZE project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# BASE_DIR: المسار الجذري للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent


# ⚠️ إعدادات التطوير (غيّرها في الإنتاج)
SECRET_KEY = 'django-insecure-&b#=aus5b*g!!^whp6dm=68kj9mb88g(#t&tf9l#$&!hmi-=#_'
DEBUG = True
ALLOWED_HOSTS = []  # أضف نطاقك عند النشر، مثلاً ['yourdomain.com']


# ✅ التطبيقات المثبتة
INSTALLED_APPS = [
    # تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ✅ تطبيقات المشروع
    'store',
    'orders',
    'accounts',
]


# ✅ الـ Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # لدعم الترجمة
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ✅ إعدادات المسارات
ROOT_URLCONF = 'YaserZE.urls'

# ✅ إعدادات القوالب
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # يمكنك إضافة مجلدات قوالب مخصصة لاحقًا
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'YaserZE.wsgi.application'


# ✅ إعداد قاعدة البيانات (افتراضي SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ✅ التحقق من كلمات المرور
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ✅ اللغة والتوقيت (تعريب كامل للنظام)
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True
USE_L10N = True  # تنسيق التواريخ والأرقام حسب اللغة
USE_TZ = True


# ✅ الملفات الثابتة (Static Files)
STATIC_URL = 'static/'


# ✅ مفتاح الحقول الافتراضي
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
